criação da migrate categoria
lswolf/beacademy-devstart-turquesa pull request #15
Opened 2022-06-28 15:53 UTC by Pablohenrique2

criação da migrate categoria.

verifiquem se os códigos estão , ok.

2022-06-28 16:21 UTC, Bethania-Freitas approved these changes

2022-06-28 22:11 UTC, lswolf requested changes
Em vez de categories tem de colocar como name no campo strings

2022-06-30 01:33 UTC, amcarv1 requested changes
Não acho que seja interessante criar uma coluna da tabela com o mesmo nome da categoria.


> public function up()
>     {
>         Schema::create('categories', function (Blueprint $table) {
>             $table->id();
>             $table->string('categories', 100);
>             $table->timestamps();
>         });
>     }
> 

Minha sugestão de código:

> public function up()
>     {
>         Schema::create('categories', function (Blueprint $table) {
>             $table->id();
>             $table->string('name', 100); // name ao invés de categories
>             $table->timestamps();
>         });
>     }
>

2022-06-30 11:43 UTC, amcarv1 approved these changes
Aprovado

2022-06-30 20:38 UTC, lswolf reviewed
perfeito

2022-06-30 20:38 UTC, lswolf approved these changes

2022-07-01 23:35 UTC, arthur-fellipe approved these changes

2022-07-03 13:17 UTC, merged