Inclui a migration de pedidos
lswolf/beacademy-devstart-turquesa pull request #19
Opened 2022-06-30 03:27 UTC by arthur-fellipe

Criação do migration de pedidos. É necessário verificar coesão com as outras tabelas.

2022-06-30 18:13 UTC, arthur-fellipe commented
Código corrigido com as mudanças sugeridas. Além disso, para atender à exigência do Projeto Empresarial, estou sentindo falta de uma conexão com a tabela de produtos no carrinho, que podemos implementar posteriormente.

2022-06-30 20:35 UTC, lswolf commented
> Código corrigido com as mudanças sugeridas. Além disso, para atender à exigência do Projeto Empresarial, estou sentindo falta de uma conexão com a tabela de produtos no carrinho, que podemos implementar posteriormente.
 Ela não precisa ligar com os produtos no carrinho pq vc pode pegar os dados com o dado do carrinho, depois explico melhor

2022-06-30 20:37 UTC, lswolf requested changes
Mudar requests para order, como está errado no inglês, mas é só isso, bom trabalho!

2022-07-01 22:50 UTC, Pablohenrique2 approved these changes

2022-07-03 13:12 UTC, lswolf approved these changes

2022-07-03 14:36 UTC, GeanFerreira approved these changes

2022-07-04 11:20 UTC, amcarv1 approved these changes

2022-07-05 00:50 UTC, DanielPinheir approved these changes

2022-07-05 00:53 UTC, merged